-- Clarify the initial research briefs without changing their claims or source dates.
UPDATE problem_text SET title = 'Courier payments are hard to track.', summary = 'Online businesses need to see which orders were delivered, returned and paid for across different couriers.', context = 'Order details, delivery updates and payments sit in separate records. Find out how much work it takes to match them and whether businesses need help doing it.' WHERE problem_id = 'courier-settlement' AND locale = 'en';
UPDATE problem_text SET title = 'কুরিয়ারের পাওনা মেলানো কঠিন।', summary = 'একাধিক কুরিয়ারে পণ্য পাঠালে কোন অর্ডার পৌঁছেছে, ফেরত এসেছে আর টাকা পাওয়া গেছে, তা মিলিয়ে দেখতে হয়।' WHERE problem_id = 'courier-settlement' AND locale = 'bn';
UPDATE problem_text SET title = 'Garment offcuts need the right buyer.', context = 'Find out why some fabric offcuts remain unsold. Buyers may be unsure of the material or quality, or collection may cost too much. Check whether better information would help before building a marketplace.', unknown = 'Would clearer quality checks and regular supply earn enough to cover inspection, transport and the people arranging the sale?' WHERE problem_id = 'garment-offcuts' AND locale = 'en';
UPDATE problem_text SET customer = 'A food supplier who makes regular deliveries but cannot fill a refrigerated vehicle.', unknown = 'Can suppliers share the same route, timing and storage conditions? Would the price cover the trip, handling and possible spoilage?' WHERE problem_id = 'shared-cold-delivery' AND locale = 'en';
UPDATE problem_text SET summary = 'Order teams may spend too much time replaying messages to check products, quantities and addresses.', context = 'Find out whether taking orders from voice notes causes mistakes or delays. We have not yet interviewed customers about this problem.' WHERE problem_id = 'bangla-order-notes' AND locale = 'en';
UPDATE problem_text SET title = 'Produce packaging is hard to reuse.', summary = 'Fruit and vegetable suppliers may benefit from sturdy crates that they can get back after each delivery.', context = 'Find out what suppliers spend on packaging and how often goods are damaged in transit. Then check whether reusable crates could help. We have not measured those costs yet.' WHERE problem_id = 'produce-crates' AND locale = 'en';
UPDATE problem_text SET title = 'Finding the right machine repairer takes time.', customer = 'The manager of a small factory with a common type of machine.', context = 'Ask managers what happened during their last breakdown. Was finding a technician the difficult part, or was it getting parts or agreeing on payment?' WHERE problem_id = 'factory-maintenance' AND locale = 'en';
UPDATE approach_text SET title = 'Track courier payments in one place', description = 'With the business’s permission, upload its order and payment spreadsheets. Match each order to a payment and flag anything that does not match. Let the business correct mistakes and see a record of changes.', business_model = 'Try a monthly fee. Check whether businesses with more orders would pay more.', steps_json = '["Ask three business owners to show how they checked their latest courier payment. Remove private customer details first.", "Match one week of orders and payments by hand. Note missing order numbers, fee differences and the time it takes.", "Show what did not match. Offer to do it again for a fee before building connections to courier systems."]', signal = 'A business sends another batch and agrees to pay for regular help.' WHERE approach_id = 'courier-settlement-approach' AND locale = 'en';
UPDATE approach_text SET description = 'Start with one type of fabric offcut. Record its material, colour, cleanliness, weight and collection details. Help one factory and one buyer complete a sale before building a listing site.', business_model = 'Try a clearly stated fee for arranging a sale, checking quality or collecting the material.' WHERE approach_id = 'garment-offcuts-approach' AND locale = 'en';
UPDATE approach_text SET title = 'Share space in a refrigerated delivery', description = 'Work with an operator who already handles this type of food safely. Match spare space with suppliers who need the same route, temperature and delivery time.', business_model = 'Try a fee for each shipment you arrange. Show transport and handling costs separately.' WHERE approach_id = 'shared-cold-delivery-approach' AND locale = 'en';
UPDATE approach_text SET description = 'Turn a voice note into a draft order. Highlight anything uncertain and ask a person to check it before confirming. Begin with one business’s product list.', business_model = 'Try a monthly team subscription. Compare the fee with the time saved after checking and correcting orders.' WHERE approach_id = 'bangla-order-notes-approach' AND locale = 'en';
UPDATE approach_text SET description = 'Start with a few crates on one regular route. Record who has each crate and agree who returns, cleans and pays for damage before the first delivery.' WHERE approach_id = 'produce-crates-approach' AND locale = 'en';
UPDATE approach_text SET description = 'Find technicians whose skills you have checked for one type of machine in one area. Agree the repair work and price in advance, then record what was done.' WHERE approach_id = 'factory-maintenance-approach' AND locale = 'en';
UPDATE approach_text SET title = 'Check courier payments for a business', description = 'Use a shared spreadsheet to match a business’s orders with its courier payments. Agree which missing or incorrect payments you will help investigate.', business_model = 'Try a fixed fee for checking one week of payments. Count the hours it takes before offering ongoing help.', steps_json = '["Ask a business owner to walk you through a past courier payment.", "With permission, check a small batch by hand after removing private customer details.", "Show what you found and ask whether they would pay for you to do it again."]', signal = 'The business gets useful answers and wants to pay for another check. The fee covers your time.' WHERE approach_id = 'courier-settlement-service' AND locale = 'en';
UPDATE approach_text SET description = 'Listen to the voice note, record the order in a simple form and send the details to the customer to confirm. See whether this catches mistakes before the order is packed.', business_model = 'Try it with one team first. If other teams want help using it, test whether they would pay for setup or training.', signal = 'Customer confirmation catches mistakes and saves the team more work than it adds.' WHERE approach_id = 'bangla-order-confirmation' AND locale = 'en';
UPDATE approach_text SET title = 'এক জায়গায় কুরিয়ারের পাওনা দেখুন' WHERE approach_id = 'courier-settlement-approach' AND locale = 'bn';
UPDATE approach_text SET title = 'ব্যবসার কুরিয়ার পেমেন্ট মিলিয়ে দিন' WHERE approach_id = 'courier-settlement-service' AND locale = 'bn';
UPDATE approach_text SET title = 'ঠান্ডা রাখার গাড়িতে জায়গা ভাগ করে নিন' WHERE approach_id = 'shared-cold-delivery-approach' AND locale = 'bn';
