#!/usr/bin/env node
/**
 * Cross-references plan/content-backlog.csv (the canonical content plan) against
 * app/generated/manifest.bn.json (what actually exists on the site) so the backlog
 * stays mechanically actionable instead of drifting silently.
 *
 * Every backlog row has a canonical Path. Exact matching keeps this report
 * actionable; title-based guesses hide route drift.
 *
 * Output: plan/status-report.md
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

function parseCsv(text) {
  const rows = []
  let row = []
  let field = ''
  let inQuotes = false
  for (let i = 0; i < text.length; i++) {
    const ch = text[i]
    if (inQuotes) {
      if (ch === '"') {
        if (text[i + 1] === '"') { field += '"'; i++ } else inQuotes = false
      } else {
        field += ch
      }
    } else if (ch === '"') {
      inQuotes = true
    } else if (ch === ',') {
      row.push(field); field = ''
    } else if (ch === '\n') {
      row.push(field); rows.push(row); row = []; field = ''
    } else if (ch === '\r') {
      // skip, \n handles the line break
    } else {
      field += ch
    }
  }
  if (field.length || row.length) { row.push(field); rows.push(row) }
  return rows.filter((r) => !(r.length === 1 && r[0] === ''))
}

function loadCsv(filePath) {
  const rows = parseCsv(fs.readFileSync(filePath, 'utf8'))
  const header = rows[0]
  return rows.slice(1).map((r) => Object.fromEntries(header.map((h, i) => [h, (r[i] ?? '').trim()])))
}

const manifest = JSON.parse(fs.readFileSync(path.join(root, 'app', 'generated', 'manifest.bn.json'), 'utf8'))

const sitePages = []
for (const section of Object.values(manifest.sections)) {
  if (section.index) {
    sitePages.push({
      slug: section.index.slug,
      title: section.index.title,
      stub: section.index.stub
    })
  }
  for (const child of section.children) {
    sitePages.push({
      slug: child.slug,
      title: child.title,
      stub: child.stub
    })
  }
}

const bySlug = new Map(sitePages.map((page) => [page.slug, page]))

const backlogRows = loadCsv(path.join(root, 'plan', 'content-backlog.csv'))

const results = backlogRows.map((row) => {
  const slug = row.Path.replace(/^\//, '')
  const match = bySlug.get(slug) || null
  return { ...row, slug, match }
})

// --- Aggregate: Section x Priority counts of written / stub / missing ---
const grid = new Map()
for (const r of results) {
  const key = `${r.Section}|${r.Priority}`
  if (!grid.has(key)) grid.set(key, { written: 0, stub: 0, missing: 0 })
  const bucket = grid.get(key)
  if (!r.match) bucket.missing++
  else if (r.match.stub) bucket.stub++
  else bucket.written++
}

const sectionOrder = [...new Set(backlogRows.map((r) => r.Section))]
const priorityOrder = ['High', 'Medium', 'Low']

const missingRows = results.filter((r) => !r.match)

const totalWritten = results.filter((r) => r.match && !r.match.stub).length
const totalStub = results.filter((r) => r.match?.stub).length

let md = '# Backlog status report\n\n'
md += 'Generated by `npm run backlog:status` — cross-references `plan/content-backlog.csv` against '
md += '`app/generated/manifest.bn.json`. Regenerate after editing the backlog or writing pages; '
md += 'do not hand-edit this file.\n\n'
md += `- Backlog rows: **${backlogRows.length}**\n`
md += `- Matched to a written page: **${totalWritten}**\n`
md += `- Matched to a stub: **${totalStub}**\n`
md += `- No matching page: **${missingRows.length}**\n`
md += `- Total site pages: **${sitePages.length}** (includes hubs, journeys and policy pages)\n\n`

md += '## Section × priority\n\n'
md += '| Section | Priority | Written | Stub | Missing | Total |\n'
md += '|---|---|---|---|---|---|\n'
for (const section of sectionOrder) {
  for (const priority of priorityOrder) {
    const key = `${section}|${priority}`
    if (!grid.has(key)) continue
    const b = grid.get(key)
    const total = b.written + b.stub + b.missing
    md += `| ${section} | ${priority} | ${b.written} | ${b.stub} | ${b.missing} | ${total} |\n`
  }
}

md += '\n## Backlog rows with no matching page\n\n'
if (missingRows.length === 0) {
  md += 'No backlog rows are missing a site page.\n'
} else {
  md += `${missingRows.length} rows. Add the missing stub or correct its canonical Path.\n\n`
  md += '| Section | Subsection | Topic (English) | Priority | Path |\n'
  md += '|---|---|---|---|---|\n'
  for (const r of missingRows) {
    md += `| ${r.Section} | ${r.Subsection} | ${r['Topic (English)']} | ${r.Priority} | \`${r.slug}\` |\n`
  }
}

fs.writeFileSync(path.join(root, 'plan', 'status-report.md'), md)
console.log(`plan/status-report.md written: ${backlogRows.length} backlog rows, ${missingRows.length} unmatched`)
